### ISSUE TITLE
Typo in the URI's Defined

### ISSUE THREAD

**Issue by IdemenB** [Dansvidania/rust-camunda-client#1]
Thank you for this (auto-generated?) library, it's really useful and saved a lot of time to implement from scratch. The URI defined for the process definition API should be corrected as "process-definition". Currently it is typed as "process_definition". Please check https://docs.camunda.org/manual/latest/reference/rest/process-definition/post-start-process-instance/.

**Comment by dan-amoroso** [comment]
Hello and thanks a lot for checking it out. 

It is indeed autogenerated and I Invite you to check out the generator itself, it is a really nifty tool. I really cannot take any merit for this :)

I originally only meant to use it for my other project [camunda-worker](https://github.com/Dansvidania/camunda-worker) and I invite you to check that out as well in case you are interested in developing a camunda external task worker in Rust. Still very much in its infancy, but with some help from the community I think it could be useful.

The generated code clearly is not 100% perfect, so I will make sure to correct the typo, check if there are more instances of underscores in the urls, and republish the crate. 


Thanks again for the help

**Comment by IdemenB** [comment]
Anyway, as I would not know that such a tool existed, I'd try to implement all those endpoints by my self (Camunda is a key tool for our projects)  so it's been really helpful.  I already benefited from camunda-worker, too. Do you heavily use Camunda as well? If yes, we could be in a very limited group of people working with it in a Rust environment, so we should keep in touch :)

**Comment by dan-amoroso** [comment]
It indeed seems to be a very small niche, and I would be delighted to keep in touch. 

I was using Camunda quite heavily for a contract in the past; despite the end of that contract I found this to be an interesting way to learn more about Rust -I am still very much a beginner- with the side effect of developing a potentially useful library. 

I would appreciate feedback for camunda-worker both regarding the usability of the API and the code itself, as I can imagine it can use some improvements.

Thanks again
